# Generated by Django 2.1.3 on 2018-11-06 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.DecimalField(decimal_places=2, max_digits=7)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dategame', models.DateTimeField()),
                ('place', models.CharField(default='Skra', max_length=127)),
                ('game_price', models.DecimalField(decimal_places=2, default='220', max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('surname', models.CharField(default='', max_length=42)),
                ('description', models.TextField(default='')),
                ('email', models.EmailField(blank=True, max_length=127, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('new_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pilka.Player')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pilka.Game')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='player',
            field=models.ManyToManyField(through='pilka.Series', to='pilka.Player'),
        ),
    ]
