# Generated by Django 2.1.3 on 2018-11-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilka', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=127),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='surname',
            field=models.CharField(blank=True, max_length=42),
        ),
    ]
