# Generated by Django 2.1.3 on 2018-11-07 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pilka', '0002_auto_20181106_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='data',
        ),
    ]
