# Generated by Django 2.1.3 on 2018-11-07 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pilka', '0003_remove_series_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='new_game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pilka.Game'),
        ),
        migrations.AlterField(
            model_name='series',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pilka.Player'),
        ),
    ]
